### PR TITLE
#7 - fixed copyright section

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this PR.

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@longtimeago it's yours, please review

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by dmarkov** [comment]
@longtimeago Much obliged! I've added **17 mins** to your account in payment "50593250"

+17 added to your rating, current score is: [+1280](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
