### PR TITLE
Got rid of Cash in favor of BigDecimal

### PR DESCRIPTION
**Pull request by cyberone**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@yegor256 this pull request is for you, please review

**Comment by yegor256** [comment]
@cyberone you didn't delete `Cash.java`, right? why?

**Comment by cyberone** [comment]
@yegor256 my fault. Forgot to do the last step. Check now please.

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 done, I added **18 mins** in payment `000-08c1047e`; +18 added to your rating, at the moment it is: [+4352](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
