### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 I just added **16 mins** to your account, many thanks for your contribution (000-e936c3df).. 97 hours and 10 mins spent here

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+4448](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
